kind: Deployment
apiVersion: apps/v1
metadata:
  name: flask-deployment
  namespace: flask-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
   metadata:
     labels:
       app: flask-app
   spec:
     containers:
     - name: flask-app
       image: root938/flask-two-tier-web:1.1
       ports:
       - containerPort: 5000
       env:
         - name: DB_HOST
           value: "postgres"
         - name: DB_PORT
           value: "5432"
         - name: DB_USER
           value: "postgres"
         - name: DB_PASSWORD
           value: "postgres"
         - name: DB_NAME
           value: "userdb"

---
kind: Service
apiVersion: v1
metadata:
  name: flask-service
  namespace: flask-app
spec:
  selector:
    app: flask-app
  ports:
   - name: flask-app
     port: 5000
     targetPort: 5000
  type: ClusterIP
           
